### ISSUE TITLE
Unable to run 2 containers side by side

### ISSUE THREAD

**Issue by vvdbosch** [nextgenhealthcare/connect-docker#1]
Hello,

Trying to use the nextgenhealthcare/connect image on docker.
Unfortunately I am not able to run 2 different containers side by side on the same machine. 
I tried with 
docker run --name Mirth1 -d -p 8443:8443 nextgenhealthcare/connect
docker run --name Mirth**2** -d -p 844**4**:844**4** nextgenhealthcare/connect
And also with docker-compose

version: "3"
services:
        "1":
                image: nextgenhealthcare/connect
                ports:
                        - 8080:8080/tcp
                        - 8443:8443/tcp

        "2":
                image: nextgenhealthcare/connect
                ports:
                        - 8081:8081/tcp
                        - 8444:8444/tcp

Both containers are running but only 1 is accessible. 
When I have a look at the running containers and their ports, it looks like the connect image always adds the 8443/tcp as additional port to the second container:

`CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
357d322fea21        nextgenhealthcare/connect   "/entrypoint.sh ./mc…"   10 seconds ago      Up 8 seconds        0.0.0.0:8081->8081/tcp, 0.0.0.0:8444->8444/tcp, 8443/tcp   mirth_2_1
13f562a8c373        nextgenhealthcare/connect   "/entrypoint.sh ./mc…"   10 seconds ago      Up 9 seconds        0.0.0.0:8080->8080/tcp, 0.0.0.0:8443->8443/tcp             mirth_1_1
`

Any advice on how I can run multiple connect containers on the same docker installation? 

Thanks!!

**Comment by cturczynskyj** [comment]
By default, Connect will use 8080 and 8443 for its ports. These are the default values in mirth.properties. It sounds like you want to use 8080/8443 for one server and 8081/8444 for another and this is totally doable. You just need to either configure Connect to use those ports or expose a port mapping that coincides with the knowledge that Connect is using 8080/8443 by default.

For example, your Docker compose file could look like this (note the port mappings on mc2):
```
version: "3.1"
services:
  mc1:
    image: nextgenhealthcare/connect
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
  mc2:
    image: nextgenhealthcare/connect
    ports:
      - 8081:8080/tcp
      - 8444:8443/tcp
```
You should be able to do the same thing with docker run:
```
docker run --name Mirth1 -d -p 8080:8080 -p 8443:8443 nextgenhealthcare/connect
docker run --name Mirth2 -d -p 8081:8080 -p 8444:8443 nextgenhealthcare/connect
```
Alternatively, you could change the ports that Connect is using internally by using environment variables. Here's an example compose file:
```
version: "3.1"
services:
  mc1:
    image: nextgenhealthcare/connect
    environment:
      - _MP_HTTP_PORT=8080
      - _MP_HTTPS_PORT=8443
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
  mc2:
    image: nextgenhealthcare/connect
    environment:
      - _MP_HTTP_PORT=8081
      - _MP_HTTPS_PORT=8444
    ports:
      - 8081:8081/tcp
      - 8444:8444/tcp
```
The good thing about doing it this way is that the Administrator login screen will default to the right port.

![Screen Shot 2019-12-02 at 6 09 26 PM](https://user-images.githubusercontent.com/15792647/70015192-7ba1bf00-1531-11ea-95dc-6891892d9611.png)
