### ISSUE TITLE
MySQL is unavailable. Aborting.

### ISSUE THREAD

**Issue by rstoermer** [nextgenhealthcare/connect-docker#2]
I can't get Connect to run with MySQL (Ran great before without mysql). For some reason the connect container can't connect to mysql, although other containers (like Adminer/ phpmyadmin) can, with the hostname connectdb. With the image 3.8.1 I am getting:

connect_1    | trying to connect to mysql
connect_1    | MySQL is unavailable. Aborting.

With the image 3.8.1-zulu-alpine-jdk I am getting:

connect_1    | /entrypoint.sh: line 192:   215 Done                    echo $dbpassword
connect_1    |        216 Segmentation fault      | mysql -h "$dbhost" -p -P "$dbport" -u "$dbusername" -e 'SHOW DATABASES' > /dev/null 2>&1
connect_1    | /entrypoint.sh: line 192:   218 Done                    echo $dbpassword
connect_1    |        219 Segmentation fault      | mysql -h "$dbhost" -p -P "$dbport" -u "$dbusername" -e 'SHOW DATABASES' > /dev/null 2>&1
connect_1    | MySQL is unavailable. Aborting.
smart-or-data-broker_connect_1 exited with code 1

Seems like the information from my env file is not passed into connect? With all other containers in the same docker-compose.yml it works well

However even without the env file, running e.g. "docker run --name connect -p 8443:8443 -e DATABASE='mysql' -e DATABASE_URL='jdbc:mysql://connectdb:3306/mirthdb' nextgenhealthcare/connect:3.8.1-zulu-alpine" produces the same error. I know the password and so on are missing, however the host and port are not found either:

219 Segmentation fault      | mysql -h "$dbhost" -p -P "$dbport" -u "$dbusername" -e 'SHOW DATABASES' > /dev/null 2>&1

My docker-compose looks like this:

```
 connect:
    image: nextgenhealthcare/connect:3.8.1
    ports:
      - 8443:8443/tcp
      - 6554:6554/tcp
    environment:
      - DATABASE=mysql
      - DATABASE_URL=jdbc:mysql://connectdb:3306/mirthdb
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./connect/appdata:/opt/connect/appdata
  connectdb:
    image: mysql:8
    restart: always
    volumes:
      - ./connectdb/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=mirthdb
      - MYSQL_USER=${DB_USER}
      - MYSQL_USER_PASSWORD=${DB_USER_PASSWORD}
    ports: 
      - 3306:3306/tcp
```
